# Stage 1: Builder
FROM python:3.11-slim AS builder
WORKDIR /app

# Додаємо залежності для збірки
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Встановлюємо версію ТІЛЬКИ для CPU (вона набагато менша!)
RUN pip install --no-cache-dir --target=/python-deps \
    torch torchvision --index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir --target=/python-deps pillow

# Stage 2: Final
FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /python-deps /usr/local/lib/python3.11/site-packages/
ENV PYTHONPATH="/usr/local/lib/python3.11/site-packages"
COPY model.pt inference.py .
ENTRYPOINT ["python", "inference.py"]